version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/my-acorad-front/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
